"""create mpc_table

Revision ID: 8c3f73f0ede0
Revises: 7bc901895107
Create Date: 2025-12-18 05:39:58.556171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c3f73f0ede0'
down_revision = '7bc901895107'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mpc_table',
    sa.Column('designation', sa.Text(), nullable=False),
    sa.Column('jd', sa.Double(), nullable=False),
    sa.Column('ra', sa.Double(), nullable=False),
    sa.Column('dec', sa.Double(), nullable=False),
    sa.Column('pm_ra', sa.Double(), nullable=False),
    sa.Column('pm_dec', sa.Double(), nullable=False),
    sa.Column('position_x', sa.Double(), nullable=False),
    sa.Column('position_y', sa.Double(), nullable=False),
    sa.Column('position_z', sa.Double(), nullable=False),
    sa.Column('velocity_x', sa.Double(), nullable=False),
    sa.Column('velocity_y', sa.Double(), nullable=False),
    sa.Column('velocity_z', sa.Double(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('designation')
    )
    op.create_index(op.f('ix_mpc_table_created_at'), 'mpc_table', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mpc_table_created_at'), table_name='mpc_table')
    op.drop_table('mpc_table')
    # ### end Alembic commands ###
